### ISSUE TITLE
How to run olivar on multiple fasta?

### ISSUE THREAD

**Issue by wangzhichao1990** [treangenlab/Olivar#23]
Hi, 
I have a multiple fasta, and I have run olivar build for each seq.
What should I do next?
Thanks.

**Comment by mxwang66** [comment]
@wangzhichao1990 All `.olvr` files shoud be placed in the same directory to run `olivar tiling` on all of them. Check the instructions [here](https://github.com/treangenlab/Olivar#2-design-tiled-amplicons). Also see arguments of olivar tiling [here](https://github.com/treangenlab/Olivar#sub-command-tiling).

**Comment by wangzhichao1990** [comment]
It doesn't work.
![image](https://github.com/user-attachments/assets/ad22205b-32ba-4f95-9b7e-589a98b52c31)

**Comment by mxwang66** [comment]
@wangzhichao1990 which version of Olivar is installed on your system? The line number doesn't seems to match the latest version 1.2.1 (it matches 1.1.5). The version has to be ≥1.2 to support multiple `.olvr` input.

**Comment by wangzhichao1990** [comment]
olivar version is v1.1.5.
I will update it and try again.
Thanks.

**Comment by wangzhichao1990** [comment]
It works.

**Comment by mxwang66** [comment]
@wangzhichao1990 thanks for the update, good to know it worked!
